export type PlayerDef = {
  teamExternalId: string;
  name: string;
  position: 'GOALKEEPER' | 'DEFENDER' | 'MIDFIELDER' | 'FORWARD';
  nationality: string;
  number?: number;
  source: string;
};

// 48 squads × 25 players = 1,200 players
// Composition per squad: 3 GK · 8 DEF · 8 MID · 6 FW
const S = 'fifa-wc2026';
const gk = (t: string, n: string, nat: string, num?: number): PlayerDef => ({
  teamExternalId: t,
  name: n,
  position: 'GOALKEEPER',
  nationality: nat,
  source: S,
  ...(num !== undefined ? { number: num } : {}),
});
const df = (t: string, n: string, nat: string, num?: number): PlayerDef => ({
  teamExternalId: t,
  name: n,
  position: 'DEFENDER',
  nationality: nat,
  source: S,
  ...(num !== undefined ? { number: num } : {}),
});
const mf = (t: string, n: string, nat: string, num?: number): PlayerDef => ({
  teamExternalId: t,
  name: n,
  position: 'MIDFIELDER',
  nationality: nat,
  source: S,
  ...(num !== undefined ? { number: num } : {}),
});
const fw = (t: string, n: string, nat: string, num?: number): PlayerDef => ({
  teamExternalId: t,
  name: n,
  position: 'FORWARD',
  nationality: nat,
  source: S,
  ...(num !== undefined ? { number: num } : {}),
});

export const PLAYERS: PlayerDef[] = [

  // ── Group A: Mexico ──────────────────────────────────────────────────────
  gk('MEX', 'Guillermo Ochoa', 'Mexican', 1),
  gk('MEX', 'Luis Ángel Malagón', 'Mexican', 13),
  gk('MEX', 'Rodolfo Cota', 'Mexican', 23),
  df('MEX', 'Jorge Sánchez', 'Mexican', 2),
  df('MEX', 'César Montes', 'Mexican', 3),
  df('MEX', 'Néstor Araujo', 'Mexican', 4),
  df('MEX', 'Gerardo Arteaga', 'Mexican', 22),
  df('MEX', 'Kevin Álvarez', 'Mexican', 19),
  df('MEX', 'Johan Vásquez', 'Mexican', 15),
  df('MEX', 'Jesús Angulo', 'Mexican', 17),
  df('MEX', 'Luis Rodríguez', 'Mexican', 16),
  mf('MEX', 'Edson Álvarez', 'Mexican', 4),
  mf('MEX', 'Héctor Herrera', 'Mexican', 16),
  mf('MEX', 'Carlos Rodríguez', 'Mexican', 8),
  mf('MEX', 'Orbelín Pineda', 'Mexican', 14),
  mf('MEX', 'Roberto Alvarado', 'Mexican', 10),
  mf('MEX', 'Uriel Antuna', 'Mexican', 7),
  mf('MEX', 'Sebastián Córdova', 'Mexican', 21),
  mf('MEX', 'Charly Rodríguez', 'Mexican', 18),
  fw('MEX', 'Hirving Lozano', 'Mexican', 9),
  fw('MEX', 'Alexis Vega', 'Mexican', 11),
  fw('MEX', 'Santiago Giménez', 'Mexican', 20),
  fw('MEX', 'Henry Martín', 'Mexican', 12),
  fw('MEX', 'Raúl Jiménez', 'Mexican', 9),
  fw('MEX', 'Rogelio Funes Mori', 'Mexican', 24),

  // ── Group A: South Africa ─────────────────────────────────────────────────
  gk('RSA', 'Ronwen Williams', 'South African', 1),
  gk('RSA', 'Veli Mothwa', 'South African', 16),
  gk('RSA', 'Bruce Bvuma', 'South African', 23),
  df('RSA', 'Siyanda Xulu', 'South African', 2),
  df('RSA', 'Sifiso Hlanti', 'South African', 3),
  df('RSA', 'Rushine De Reuck', 'South African', 5),
  df('RSA', 'Thibang Phete', 'South African', 6),
  df('RSA', 'Reeve Frosler', 'South African', 22),
  df('RSA', 'Terrence Mashego', 'South African', 15),
  df('RSA', 'Sipho Mbule', 'South African', 17),
  df('RSA', 'Bradley Cross', 'South African', 26),
  mf('RSA', 'Teboho Mokoena', 'South African', 8),
  mf('RSA', 'Bongani Zungu', 'South African', 10),
  mf('RSA', 'Ethan Brooks', 'South African', 4),
  mf('RSA', 'Yusuf Maart', 'South African', 14),
  mf('RSA', 'Miguel Timm', 'South African', 18),
  mf('RSA', 'Goodman Mosele', 'South African', 7),
  mf('RSA', 'Njabulo Vilakazi', 'South African', 13),
  mf('RSA', 'Sibongiseni Mthethwa', 'South African', 19),
  fw('RSA', 'Percy Tau', 'South African', 11),
  fw('RSA', 'Lyle Foster', 'South African', 9),
  fw('RSA', 'Themba Zwane', 'South African', 24),
  fw('RSA', 'Evidence Makgopa', 'South African', 12),
  fw('RSA', 'Bongokuhle Hlongwane', 'South African', 20),
  fw('RSA', 'Oswin Appollis', 'South African', 25),

  // ── Group A: South Korea ──────────────────────────────────────────────────
  gk('KOR', 'Jo Hyeon-woo', 'South Korean', 1),
  gk('KOR', 'Kim Seung-gyu', 'South Korean', 12),
  gk('KOR', 'Song Bum-keun', 'South Korean', 21),
  df('KOR', 'Kim Min-jae', 'South Korean', 3),
  df('KOR', 'Kim Young-gwon', 'South Korean', 5),
  df('KOR', 'Kim Jin-su', 'South Korean', 15),
  df('KOR', 'Yoon Jong-gyu', 'South Korean', 14),
  df('KOR', 'Lee Ki-je', 'South Korean', 17),
  df('KOR', 'Kim Moon-hwan', 'South Korean', 2),
  df('KOR', 'Hong Chul', 'South Korean', 23),
  df('KOR', 'Kwon Kyung-won', 'South Korean', 6),
  mf('KOR', 'Lee Kang-in', 'South Korean', 10),
  mf('KOR', 'Jung Woo-young', 'South Korean', 16),
  mf('KOR', 'Hwang In-beom', 'South Korean', 8),
  mf('KOR', 'Son Jun-ho', 'South Korean', 13),
  mf('KOR', 'Paik Seung-ho', 'South Korean', 7),
  mf('KOR', 'Cho Gue-sung', 'South Korean', 18),
  mf('KOR', 'Kim Ji-soo', 'South Korean', 19),
  mf('KOR', 'Lee Jae-sung', 'South Korean', 11),
  fw('KOR', 'Son Heung-min', 'South Korean', 7),
  fw('KOR', 'Hwang Hee-chan', 'South Korean', 9),
  fw('KOR', 'Oh Hyeon-gyu', 'South Korean', 20),
  fw('KOR', 'Cho Hyun-woo', 'South Korean', 22),
  fw('KOR', 'Lim Sang-hyup', 'South Korean', 24),
  fw('KOR', 'Jeong Woo-yeong', 'South Korean', 25),

  // ── Group A: Czechia ─────────────────────────────────────────────────────
  gk('CZE', 'Jiří Pavlenka', 'Czech', 1),
  gk('CZE', 'Tomáš Vaclík', 'Czech', 12),
  gk('CZE', 'Matěj Kovář', 'Czech', 23),
  df('CZE', 'Tomáš Čvančara', 'Czech', 3),
  df('CZE', 'Ondřej Kúdela', 'Czech', 4),
  df('CZE', 'Tomáš Holeš', 'Czech', 5),
  df('CZE', 'Pavel Kadeřábek', 'Czech', 2),
  df('CZE', 'Jan Bořil', 'Czech', 15),
  df('CZE', 'Vladimír Coufal', 'Czech', 6),
  df('CZE', 'David Zima', 'Czech', 22),
  df('CZE', 'Lukáš Hrádecký', 'Czech', 17),
  mf('CZE', 'Tomáš Souček', 'Czech', 8),
  mf('CZE', 'Marek Suchý', 'Czech', 13),
  mf('CZE', 'Lukáš Provod', 'Czech', 7),
  mf('CZE', 'Alex Král', 'Czech', 14),
  mf('CZE', 'Michal Sadílek', 'Czech', 16),
  mf('CZE', 'Matěj Juránek', 'Czech', 18),
  mf('CZE', 'Ondřej Lingr', 'Czech', 19),
  mf('CZE', 'Lukáš Kalvach', 'Czech', 20),
  fw('CZE', 'Patrik Schick', 'Czech', 9),
  fw('CZE', 'Adam Hložek', 'Czech', 11),
  fw('CZE', 'Ondřej Kovář', 'Czech', 10),
  fw('CZE', 'Jan Kuchta', 'Czech', 21),
  fw('CZE', 'Mojmír Chytil', 'Czech', 24),
  fw('CZE', 'Václav Jurečka', 'Czech', 25),

  // ── Group B: Canada ───────────────────────────────────────────────────────
  gk('CAN', 'Milan Borjan', 'Canadian', 1),
  gk('CAN', 'Dayne St. Clair', 'Canadian', 12),
  gk('CAN', 'James Pantemis', 'Canadian', 23),
  df('CAN', 'Alistair Johnston', 'Canadian', 2),
  df('CAN', 'Kamal Miller', 'Canadian', 3),
  df('CAN', 'Steven Vitória', 'Canadian', 4),
  df('CAN', 'Doneil Henry', 'Canadian', 5),
  df('CAN', 'Richie Laryea', 'Canadian', 22),
  df('CAN', 'Derek Cornelius', 'Canadian', 15),
  df('CAN', 'Sam Adekugbe', 'Canadian', 17),
  df('CAN', 'Liam Fraser', 'Canadian', 16),
  mf('CAN', 'Stephen Eustaquio', 'Canadian', 7),
  mf('CAN', 'Jonathan Osorio', 'Canadian', 21),
  mf('CAN', 'Mark-Anthony Kaye', 'Canadian', 14),
  mf('CAN', 'Atiba Hutchinson', 'Canadian', 13),
  mf('CAN', 'Ismaël Koné', 'Canadian', 8),
  mf('CAN', 'Tajon Buchanan', 'Canadian', 11),
  mf('CAN', 'Victor Loturi', 'Canadian', 18),
  mf('CAN', 'Mathieu Choiniére', 'Canadian', 19),
  fw('CAN', 'Alphonso Davies', 'Canadian', 10),
  fw('CAN', 'Jonathan David', 'Canadian', 9),
  fw('CAN', 'Cyle Larin', 'Canadian', 17),
  fw('CAN', 'Lucas Cavallini', 'Canadian', 20),
  fw('CAN', 'Junior Hoilett', 'Canadian', 24),
  fw('CAN', 'Theo Bair', 'Canadian', 25),

  // ── Group B: Bosnia and Herzegovina ──────────────────────────────────────
  gk('BIH', 'Armin Gigović', 'Bosnian', 1),
  gk('BIH', 'Ibrahim Šehić', 'Bosnian', 12),
  gk('BIH', 'Amer Šporaković', 'Bosnian', 23),
  df('BIH', 'Sead Kolašinac', 'Bosnian', 5),
  df('BIH', 'Ermin Bičakčić', 'Bosnian', 4),
  df('BIH', 'Anel Ahmedhodžić', 'Bosnian', 6),
  df('BIH', 'Eldar Ćivić', 'Bosnian', 2),
  df('BIH', 'Almir Lenjani', 'Bosnian', 3),
  df('BIH', 'Nikola Vuković', 'Bosnian', 16),
  df('BIH', 'Amar Dedić', 'Bosnian', 22),
  df('BIH', 'Miroslav Stevanović', 'Bosnian', 17),
  mf('BIH', 'Miralem Pjanić', 'Bosnian', 8),
  mf('BIH', 'Rade Krunić', 'Bosnian', 14),
  mf('BIH', 'Haris Hajradinović', 'Bosnian', 10),
  mf('BIH', 'Rusmir Hadžibulić', 'Bosnian', 13),
  mf('BIH', 'Marko Janković', 'Bosnian', 7),
  mf('BIH', 'Benjamin Verbič', 'Bosnian', 19),
  mf('BIH', 'Kenan Kodro', 'Bosnian', 15),
  mf('BIH', 'Alen Halilović', 'Bosnian', 18),
  fw('BIH', 'Edin Džeko', 'Bosnian', 9),
  fw('BIH', 'Ermedin Demirović', 'Bosnian', 11),
  fw('BIH', 'Armin Hodžić', 'Bosnian', 20),
  fw('BIH', 'Senad Lulić', 'Bosnian', 21),
  fw('BIH', 'Vedad Ibišević', 'Bosnian', 24),
  fw('BIH', 'Nejc Skubic', 'Bosnian', 25),

  // ── Group B: Qatar ───────────────────────────────────────────────────────
  gk('QAT', 'Saad Al Sheeb', 'Qatari', 1),
  gk('QAT', 'Meshaal Barsham', 'Qatari', 12),
  gk('QAT', 'Yousef Hassan', 'Qatari', 23),
  df('QAT', 'Pedro Miguel', 'Qatari', 2),
  df('QAT', 'Bassam Al-Rawi', 'Qatari', 5),
  df('QAT', 'Tarek Salman', 'Qatari', 4),
  df('QAT', 'Homam Ahmed', 'Qatari', 16),
  df('QAT', 'Abdelkarim Hassan', 'Qatari', 3),
  df('QAT', 'Musaab Khidir', 'Qatari', 6),
  df('QAT', 'Assim Madibo', 'Qatari', 17),
  df('QAT', 'Ro-Ro', 'Qatari', 22),
  mf('QAT', 'Karim Boudiaf', 'Qatari', 8),
  mf('QAT', 'Ali Asad', 'Qatari', 14),
  mf('QAT', 'Ismail Mohammad', 'Qatari', 10),
  mf('QAT', 'Salem Al-Hajri', 'Qatari', 7),
  mf('QAT', 'Mohammed Muntari', 'Qatari', 13),
  mf('QAT', 'Hassan Al-Haydos', 'Qatari', 11),
  mf('QAT', 'Jassem Gaber', 'Qatari', 15),
  mf('QAT', 'Yusuf Abdurisag', 'Qatari', 19),
  fw('QAT', 'Almoez Ali', 'Qatari', 19),
  fw('QAT', 'Akram Afif', 'Qatari', 11),
  fw('QAT', 'Edmilson Junior', 'Qatari', 20),
  fw('QAT', 'Ahmed Alaaeldin', 'Qatari', 9),
  fw('QAT', 'Khalid Muneer', 'Qatari', 21),
  fw('QAT', 'Naif Al-Hadhrami', 'Qatari', 25),

  // ── Group B: Switzerland ──────────────────────────────────────────────────
  gk('SUI', 'Yann Sommer', 'Swiss', 1),
  gk('SUI', 'Yvon Mvogo', 'Swiss', 12),
  gk('SUI', 'Jonas Omlin', 'Swiss', 21),
  df('SUI', 'Manuel Akanji', 'Swiss', 5),
  df('SUI', 'Nico Elvedi', 'Swiss', 4),
  df('SUI', 'Silvan Widmer', 'Swiss', 2),
  df('SUI', 'Ricardo Rodríguez', 'Swiss', 13),
  df('SUI', 'Fabian Schär', 'Swiss', 6),
  df('SUI', 'Kevin Mbabu', 'Swiss', 22),
  df('SUI', 'Jordan Lotomba', 'Swiss', 15),
  df('SUI', 'Cedric Zesiger', 'Swiss', 16),
  mf('SUI', 'Granit Xhaka', 'Swiss', 10),
  mf('SUI', 'Xherdan Shaqiri', 'Swiss', 23),
  mf('SUI', 'Remo Freuler', 'Swiss', 8),
  mf('SUI', 'Denis Zakaria', 'Swiss', 14),
  mf('SUI', 'Djibril Sow', 'Swiss', 17),
  mf('SUI', 'Michel Aebischer', 'Swiss', 18),
  mf('SUI', 'Fabian Rieder', 'Swiss', 19),
  mf('SUI', 'Ardon Jashari', 'Swiss', 20),
  fw('SUI', 'Breel Embolo', 'Swiss', 7),
  fw('SUI', 'Haris Seferović', 'Swiss', 9),
  fw('SUI', 'Ruben Vargas', 'Swiss', 11),
  fw('SUI', 'Zeki Amdouni', 'Swiss', 24),
  fw('SUI', 'Dan Ndoye', 'Swiss', 25),
  fw('SUI', 'Christian Fassnacht', 'Swiss', 16),

  // ── Group C: Brazil ───────────────────────────────────────────────────────
  gk('BRA', 'Alisson', 'Brazilian', 1),
  gk('BRA', 'Ederson', 'Brazilian', 23),
  gk('BRA', 'Weverton', 'Brazilian', 12),
  df('BRA', 'Danilo', 'Brazilian', 2),
  df('BRA', 'Éder Militão', 'Brazilian', 3),
  df('BRA', 'Marquinhos', 'Brazilian', 4),
  df('BRA', 'Gabriel Magalhães', 'Brazilian', 24),
  df('BRA', 'Alex Sandro', 'Brazilian', 6),
  df('BRA', 'Bremer', 'Brazilian', 15),
  df('BRA', 'Guilherme Arana', 'Brazilian', 16),
  df('BRA', 'Vanderson', 'Brazilian', 22),
  mf('BRA', 'Casemiro', 'Brazilian', 5),
  mf('BRA', 'Bruno Guimarães', 'Brazilian', 8),
  mf('BRA', 'Lucas Paquetá', 'Brazilian', 10),
  mf('BRA', 'Fred', 'Brazilian', 17),
  mf('BRA', 'Fabinho', 'Brazilian', 13),
  mf('BRA', 'Gerson', 'Brazilian', 18),
  mf('BRA', 'Everton Ribeiro', 'Brazilian', 19),
  mf('BRA', 'Andreas Pereira', 'Brazilian', 20),
  fw('BRA', 'Neymar', 'Brazilian', 10),
  fw('BRA', 'Vinícius Júnior', 'Brazilian', 7),
  fw('BRA', 'Rodrygo', 'Brazilian', 11),
  fw('BRA', 'Raphinha', 'Brazilian', 21),
  fw('BRA', 'Richarlison', 'Brazilian', 9),
  fw('BRA', 'Gabriel Martinelli', 'Brazilian', 25),

  // ── Group C: Morocco ─────────────────────────────────────────────────────
  gk('MAR', 'Yassine Bounou', 'Moroccan', 1),
  gk('MAR', 'Ahmed Reda Tagnaouti', 'Moroccan', 12),
  gk('MAR', 'Anas Zniti', 'Moroccan', 23),
  df('MAR', 'Achraf Hakimi', 'Moroccan', 2),
  df('MAR', 'Romain Saïss', 'Moroccan', 5),
  df('MAR', 'Nayef Aguerd', 'Moroccan', 6),
  df('MAR', 'Noussair Mazraoui', 'Moroccan', 22),
  df('MAR', 'Adam Masina', 'Moroccan', 3),
  df('MAR', 'Jawad El Yamiq', 'Moroccan', 4),
  df('MAR', 'Achraf Dari', 'Moroccan', 15),
  df('MAR', 'Badr Benoun', 'Moroccan', 16),
  mf('MAR', 'Sofyan Amrabat', 'Moroccan', 4),
  mf('MAR', 'Azzedine Ounahi', 'Moroccan', 8),
  mf('MAR', 'Selim Amallah', 'Moroccan', 14),
  mf('MAR', 'Ilias Chair', 'Moroccan', 17),
  mf('MAR', 'Bilal El Khannouss', 'Moroccan', 10),
  mf('MAR', 'Amine Harit', 'Moroccan', 19),
  mf('MAR', 'Abde Ezzalzouli', 'Moroccan', 21),
  mf('MAR', 'Zakaria Aboukhlal', 'Moroccan', 18),
  fw('MAR', 'Hakim Ziyech', 'Moroccan', 7),
  fw('MAR', 'Youssef En-Nesyri', 'Moroccan', 9),
  fw('MAR', 'Sofiane Boufal', 'Moroccan', 11),
  fw('MAR', 'Walid Cheddira', 'Moroccan', 20),
  fw('MAR', 'Abderrazak Hamdallah', 'Moroccan', 24),
  fw('MAR', 'Ryan Mmaee', 'Moroccan', 25),

  // ── Group C: Haiti ───────────────────────────────────────────────────────
  gk('HAI', 'Johny Placide', 'Haitian', 1),
  gk('HAI', 'Duckens Nazon', 'Haitian', 12),
  gk('HAI', 'Beauchamp Jean', 'Haitian', 23),
  df('HAI', 'Mechack Jérôme', 'Haitian', 5),
  df('HAI', 'Héctor Camacho', 'Haitian', 4),
  df('HAI', 'Alain Cavé', 'Haitian', 3),
  df('HAI', 'Wilde-Donald Guerrier', 'Haitian', 2),
  df('HAI', 'Frantzdy Pierrot', 'Haitian', 6),
  df('HAI', 'Carlens Arcus', 'Haitian', 15),
  df('HAI', 'Bébé Samy', 'Haitian', 16),
  df('HAI', 'Kevin Lafrance', 'Haitian', 17),
  mf('HAI', 'Benny Augustin', 'Haitian', 8),
  mf('HAI', 'Steeven Saba', 'Haitian', 10),
  mf('HAI', 'Cheskel Gédéon', 'Haitian', 7),
  mf('HAI', 'Zachary Herivaux', 'Haitian', 14),
  mf('HAI', 'Joel Ntambwe', 'Haitian', 13),
  mf('HAI', 'Fredrick Germann', 'Haitian', 19),
  mf('HAI', 'Renold Pierre', 'Haitian', 18),
  mf('HAI', 'Kervens Belfort', 'Haitian', 20),
  fw('HAI', 'Duckens Nazon', 'Haitian', 9),
  fw('HAI', 'Jean-Éric Versini', 'Haitian', 11),
  fw('HAI', 'Frantznel Charles', 'Haitian', 21),
  fw('HAI', 'Larrys Mabiala', 'Haitian', 22),
  fw('HAI', 'Dominique Pierre', 'Haitian', 24),
  fw('HAI', 'Rodrigue Rostaing', 'Haitian', 25),

  // ── Group C: Scotland ────────────────────────────────────────────────────
  gk('SCO', 'Angus Gunn', 'Scottish', 1),
  gk('SCO', 'Craig Gordon', 'Scottish', 12),
  gk('SCO', 'Liam Kelly', 'Scottish', 23),
  df('SCO', 'Andrew Robertson', 'Scottish', 3),
  df('SCO', 'Kieran Tierney', 'Scottish', 5),
  df('SCO', 'Jack Hendry', 'Scottish', 6),
  df('SCO', 'Grant Hanley', 'Scottish', 4),
  df('SCO', 'Nathan Patterson', 'Scottish', 2),
  df('SCO', 'Liam Cooper', 'Scottish', 16),
  df('SCO', 'Greg Taylor', 'Scottish', 15),
  df('SCO', 'Ryan Porteous', 'Scottish', 22),
  mf('SCO', 'Scott McTominay', 'Scottish', 8),
  mf('SCO', 'Callum McGregor', 'Scottish', 14),
  mf('SCO', 'Billy Gilmour', 'Scottish', 10),
  mf('SCO', 'Ryan Christie', 'Scottish', 7),
  mf('SCO', 'Stuart Armstrong', 'Scottish', 17),
  mf('SCO', 'John McGinn', 'Scottish', 13),
  mf('SCO', 'Kenny McLean', 'Scottish', 18),
  mf('SCO', 'Lewis Ferguson', 'Scottish', 19),
  fw('SCO', 'Lyndon Dykes', 'Scottish', 9),
  fw('SCO', 'Che Adams', 'Scottish', 11),
  fw('SCO', 'Lawrence Shankland', 'Scottish', 20),
  fw('SCO', 'Kevin Nisbet', 'Scottish', 21),
  fw('SCO', 'Ryan Gauld', 'Scottish', 24),
  fw('SCO', 'Oli McBurnie', 'Scottish', 25),

  // ── Group D: USA ─────────────────────────────────────────────────────────
  gk('USA', 'Matt Turner', 'American', 1),
  gk('USA', 'Ethan Horvath', 'American', 12),
  gk('USA', 'Patrick Schulte', 'American', 23),
  df('USA', 'Sergiño Dest', 'American', 2),
  df('USA', 'Walker Zimmermann', 'American', 3),
  df('USA', 'Mark McKenzie', 'American', 5),
  df('USA', 'Tim Ream', 'American', 13),
  df('USA', 'DeAndre Yedlin', 'American', 22),
  df('USA', 'Joe Scally', 'American', 4),
  df('USA', 'Antonee Robinson', 'American', 6),
  df('USA', 'Chris Richards', 'American', 14),
  mf('USA', 'Weston McKennie', 'American', 8),
  mf('USA', 'Tyler Adams', 'American', 4),
  mf('USA', 'Yunus Musah', 'American', 6),
  mf('USA', 'Luca de la Torre', 'American', 7),
  mf('USA', 'Gio Reyna', 'American', 7),
  mf('USA', 'Brenden Aaronson', 'American', 11),
  mf('USA', 'Malik Tillman', 'American', 17),
  mf('USA', 'Caden Clark', 'American', 19),
  fw('USA', 'Christian Pulisic', 'American', 10),
  fw('USA', 'Folarin Balogun', 'American', 9),
  fw('USA', 'Timothy Weah', 'American', 21),
  fw('USA', 'Ricardo Pepi', 'American', 20),
  fw('USA', 'Josh Sargent', 'American', 24),
  fw('USA', 'Jordan Morris', 'American', 25),

  // ── Group D: Paraguay ────────────────────────────────────────────────────
  gk('PAR', 'Antony Silva', 'Paraguayan', 1),
  gk('PAR', 'Roberto Fernández', 'Paraguayan', 12),
  gk('PAR', 'Alfredo Aguilar', 'Paraguayan', 23),
  df('PAR', 'Gustavo Gómez', 'Paraguayan', 5),
  df('PAR', 'Iván Piris', 'Paraguayan', 3),
  df('PAR', 'Fabián Balbuena', 'Paraguayan', 4),
  df('PAR', 'Santiago Arzamendia', 'Paraguayan', 6),
  df('PAR', 'Marcelo Pereira', 'Paraguayan', 2),
  df('PAR', 'Omar Alderete', 'Paraguayan', 16),
  df('PAR', 'Matías Espinoza', 'Paraguayan', 22),
  df('PAR', 'Blas Riveros', 'Paraguayan', 15),
  mf('PAR', 'Miguel Almirón', 'Paraguayan', 10),
  mf('PAR', 'Ángel Romero', 'Paraguayan', 7),
  mf('PAR', 'Andrés Cubas', 'Paraguayan', 8),
  mf('PAR', 'Mathías Villasanti', 'Paraguayan', 14),
  mf('PAR', 'Richard Sánchez', 'Paraguayan', 17),
  mf('PAR', 'Hernán Pérez', 'Paraguayan', 13),
  mf('PAR', 'Rodrigo Rojas', 'Paraguayan', 19),
  mf('PAR', 'Iván Báez', 'Paraguayan', 18),
  fw('PAR', 'Julio Enciso', 'Paraguayan', 11),
  fw('PAR', 'Antonio Sanabria', 'Paraguayan', 9),
  fw('PAR', 'Roque Santa Cruz', 'Paraguayan', 20),
  fw('PAR', 'Carlos González', 'Paraguayan', 21),
  fw('PAR', 'Alejandro Romero Gamarra', 'Paraguayan', 24),
  fw('PAR', 'Brian Samudio', 'Paraguayan', 25),

  // ── Group D: Australia ───────────────────────────────────────────────────
  gk('AUS', 'Mat Ryan', 'Australian', 1),
  gk('AUS', 'Andrew Redmayne', 'Australian', 12),
  gk('AUS', 'Danny Vukovic', 'Australian', 23),
  df('AUS', 'Miloš Degenek', 'Australian', 5),
  df('AUS', 'Trent Sainsbury', 'Australian', 4),
  df('AUS', 'Joel King', 'Australian', 3),
  df('AUS', 'Nathaniel Atkinson', 'Australian', 2),
  df('AUS', 'Aziz Behich', 'Australian', 6),
  df('AUS', 'Bailey Wright', 'Australian', 14),
  df('AUS', 'Harry Souttar', 'Australian', 15),
  df('AUS', 'Fran Karačić', 'Australian', 22),
  mf('AUS', 'Riley McGree', 'Australian', 8),
  mf('AUS', 'Jackson Irvine', 'Australian', 16),
  mf('AUS', 'Aaron Mooy', 'Australian', 13),
  mf('AUS', 'Ryan Teague', 'Australian', 7),
  mf('AUS', 'Denis Genreau', 'Australian', 17),
  mf('AUS', 'Rúben Rodrigues', 'Australian', 10),
  mf('AUS', 'Connor Metcalfe', 'Australian', 18),
  mf('AUS', 'Marco Tilio', 'Australian', 19),
  fw('AUS', 'Mathew Leckie', 'Australian', 7),
  fw('AUS', 'Martin Boyle', 'Australian', 11),
  fw('AUS', 'Mitchell Duke', 'Australian', 9),
  fw('AUS', 'Jamie Maclaren', 'Australian', 20),
  fw('AUS', 'Ajdin Hrustic', 'Australian', 21),
  fw('AUS', 'Craig Goodwin', 'Australian', 25),

  // ── Group D: Türkiye ─────────────────────────────────────────────────────
  gk('TUR', 'Altay Bayındır', 'Turkish', 1),
  gk('TUR', 'Uğurcan Çakır', 'Turkish', 12),
  gk('TUR', 'Mert Günok', 'Turkish', 23),
  df('TUR', 'Zeki Çelik', 'Turkish', 2),
  df('TUR', 'Merih Demiral', 'Turkish', 3),
  df('TUR', 'Çağlar Söyüncü', 'Turkish', 4),
  df('TUR', 'Kaan Ayhan', 'Turkish', 5),
  df('TUR', 'Ridvan Yılmaz', 'Turkish', 16),
  df('TUR', 'Mert Müldür', 'Turkish', 22),
  df('TUR', 'Ahmet Kutucu', 'Turkish', 15),
  df('TUR', 'Ferdi Kadıoğlu', 'Turkish', 6),
  mf('TUR', 'Hakan Çalhanoğlu', 'Turkish', 10),
  mf('TUR', 'Samet Akaydın', 'Turkish', 8),
  mf('TUR', 'Orkun Kökçü', 'Turkish', 14),
  mf('TUR', 'Selçuk İnan', 'Turkish', 7),
  mf('TUR', 'Okay Yokuslu', 'Turkish', 17),
  mf('TUR', 'Salih Özcan', 'Turkish', 13),
  mf('TUR', 'Taylan Antalyalı', 'Turkish', 18),
  mf('TUR', 'Dorukhan Toköz', 'Turkish', 19),
  fw('TUR', 'Arda Güler', 'Turkish', 11),
  fw('TUR', 'Cenk Tosun', 'Turkish', 9),
  fw('TUR', 'Kerem Aktürkoğlu', 'Turkish', 11),
  fw('TUR', 'Umut Meraş', 'Turkish', 20),
  fw('TUR', 'İrfan Can Kahveci', 'Turkish', 21),
  fw('TUR', 'Yusuf Yazıcı', 'Turkish', 25),

  // ── Group E: Germany ─────────────────────────────────────────────────────
  gk('GER', 'Manuel Neuer', 'German', 1),
  gk('GER', 'Marc-André ter Stegen', 'German', 22),
  gk('GER', 'Kevin Trapp', 'German', 12),
  df('GER', 'Joshua Kimmich', 'German', 6),
  df('GER', 'Antonio Rüdiger', 'German', 2),
  df('GER', 'Niklas Süle', 'German', 15),
  df('GER', 'Thilo Kehrer', 'German', 4),
  df('GER', 'Jonas Hofmann', 'German', 16),
  df('GER', 'David Raum', 'German', 3),
  df('GER', 'Nico Schlotterbeck', 'German', 5),
  df('GER', 'Lukas Klostermann', 'German', 17),
  mf('GER', 'İlkay Gündoğan', 'German', 8),
  mf('GER', 'Leon Goretzka', 'German', 14),
  mf('GER', 'Jamal Musiala', 'German', 10),
  mf('GER', 'Toni Kroos', 'German', 8),
  mf('GER', 'Florian Wirtz', 'German', 17),
  mf('GER', 'Thomas Müller', 'German', 13),
  mf('GER', 'Julian Draxler', 'German', 7),
  mf('GER', 'Robert Andrich', 'German', 23),
  fw('GER', 'Kai Havertz', 'German', 7),
  fw('GER', 'Leroy Sané', 'German', 19),
  fw('GER', 'Serge Gnabry', 'German', 20),
  fw('GER', 'Niclas Füllkrug', 'German', 9),
  fw('GER', 'Lukas Nmecha', 'German', 11),
  fw('GER', 'Maximilian Beier', 'German', 21),

  // ── Group E: Curaçao ────────────────────────────────────────────────────
  gk('CUW', 'Eloy Room', 'Curaçaoan', 1),
  gk('CUW', 'Cuco Martina', 'Curaçaoan', 12),
  gk('CUW', 'Riechedly Bazoer', 'Curaçaoan', 23),
  df('CUW', 'Leandro Bacuna', 'Curaçaoan', 2),
  df('CUW', 'Rangelo Janga', 'Curaçaoan', 3),
  df('CUW', 'Etienne Reijnen', 'Curaçaoan', 5),
  df('CUW', 'Darryl Lachman', 'Curaçaoan', 4),
  df('CUW', 'Sherwin van der Graaf', 'Curaçaoan', 6),
  df('CUW', 'Raily Ignacio', 'Curaçaoan', 15),
  df('CUW', 'Juniores Martinus', 'Curaçaoan', 16),
  df('CUW', 'Gianluca Nijholt', 'Curaçaoan', 22),
  mf('CUW', 'Cuco Martina', 'Curaçaoan', 14),
  mf('CUW', 'Jarchinio Antonia', 'Curaçaoan', 10),
  mf('CUW', 'Vurnon Anita', 'Curaçaoan', 8),
  mf('CUW', 'Sheraldo Becker', 'Curaçaoan', 7),
  mf('CUW', 'Cédric van der Gun', 'Curaçaoan', 13),
  mf('CUW', 'Gevaro Nepomuceno', 'Curaçaoan', 17),
  mf('CUW', 'Gaston Salasiwa', 'Curaçaoan', 18),
  mf('CUW', 'Myron Boadu', 'Curaçaoan', 19),
  fw('CUW', 'Jurien Gaari', 'Curaçaoan', 9),
  fw('CUW', 'Gino van Kessel', 'Curaçaoan', 11),
  fw('CUW', 'Lorenzo Florentino', 'Curaçaoan', 20),
  fw('CUW', 'Nigel Thomas', 'Curaçaoan', 21),
  fw('CUW', 'Kervens Belfort', 'Curaçaoan', 24),
  fw('CUW', 'Ricardo Nieuw', 'Curaçaoan', 25),

  // ── Group E: Ivory Coast ──────────────────────────────────────────────────
  gk('CIV', 'Badra Ali Sangaré', 'Ivorian', 1),
  gk('CIV', 'Sylvain Gbohouo', 'Ivorian', 12),
  gk('CIV', 'Ismaël Diallo', 'Ivorian', 23),
  df('CIV', 'Serge Aurier', 'Ivorian', 2),
  df('CIV', 'Wilfried Singo', 'Ivorian', 5),
  df('CIV', 'Eric Bailly', 'Ivorian', 4),
  df('CIV', 'Odilon Kossounou', 'Ivorian', 3),
  df('CIV', 'Ghislain Konan', 'Ivorian', 6),
  df('CIV', 'Simon Deli', 'Ivorian', 15),
  df('CIV', 'Cheick Oumar Diallo', 'Ivorian', 16),
  df('CIV', 'Wesley Fofana', 'Ivorian', 22),
  mf('CIV', 'Ibrahim Sangaré', 'Ivorian', 8),
  mf('CIV', 'Jean Michaël Seri', 'Ivorian', 10),
  mf('CIV', 'Franck Kessie', 'Ivorian', 14),
  mf('CIV', 'Ismaël Traoré', 'Ivorian', 7),
  mf('CIV', 'Adama Traoré', 'Ivorian', 17),
  mf('CIV', 'Abdul Razak', 'Ivorian', 13),
  mf('CIV', 'Gnaly Cornet', 'Ivorian', 18),
  mf('CIV', 'Youssouf Koné', 'Ivorian', 19),
  fw('CIV', 'Sébastien Haller', 'Ivorian', 9),
  fw('CIV', 'Nicolas Pépé', 'Ivorian', 11),
  fw('CIV', 'Simon Chabli', 'Ivorian', 20),
  fw('CIV', 'Wilfried Zaha', 'Ivorian', 21),
  fw('CIV', 'Amad Diallo', 'Ivorian', 24),
  fw('CIV', 'Jonathan Bamba', 'Ivorian', 25),

  // ── Group E: Ecuador ─────────────────────────────────────────────────────
  gk('ECU', 'Hernán Galíndez', 'Ecuadorian', 1),
  gk('ECU', 'Alexander Domínguez', 'Ecuadorian', 12),
  gk('ECU', 'Kevin Minda', 'Ecuadorian', 23),
  df('ECU', 'Angelo Preciado', 'Ecuadorian', 2),
  df('ECU', 'Piero Hincapié', 'Ecuadorian', 3),
  df('ECU', 'Pervis Estupiñán', 'Ecuadorian', 16),
  df('ECU', 'Félix Torres', 'Ecuadorian', 5),
  df('ECU', 'Diego Palacios', 'Ecuadorian', 6),
  df('ECU', 'Robert Arboleda', 'Ecuadorian', 4),
  df('ECU', 'Xavier Arreaga', 'Ecuadorian', 15),
  df('ECU', 'Frickson Erazo', 'Ecuadorian', 22),
  mf('ECU', 'Moisés Caicedo', 'Ecuadorian', 10),
  mf('ECU', 'Carlos Gruezo', 'Ecuadorian', 8),
  mf('ECU', 'Jeremy Sarmiento', 'Ecuadorian', 17),
  mf('ECU', 'Alan Minda', 'Ecuadorian', 7),
  mf('ECU', 'Ángel Mena', 'Ecuadorian', 13),
  mf('ECU', 'José Cifuentes', 'Ecuadorian', 14),
  mf('ECU', 'Patrickson Delgado', 'Ecuadorian', 18),
  mf('ECU', 'John Yeboah', 'Ecuadorian', 19),
  fw('ECU', 'Enner Valencia', 'Ecuadorian', 13),
  fw('ECU', 'Gonzalo Plata', 'Ecuadorian', 11),
  fw('ECU', 'Djorkaeff Reasco', 'Ecuadorian', 21),
  fw('ECU', 'Michael Estrada', 'Ecuadorian', 9),
  fw('ECU', 'Kevin Rodríguez', 'Ecuadorian', 20),
  fw('ECU', 'Júnior Sornoza', 'Ecuadorian', 25),

  // ── Group F: Netherlands ─────────────────────────────────────────────────
  gk('NED', 'Remko Pasveer', 'Dutch', 1),
  gk('NED', 'Andries Noppert', 'Dutch', 12),
  gk('NED', 'Justin Bijlow', 'Dutch', 23),
  df('NED', 'Virgil van Dijk', 'Dutch', 4),
  df('NED', 'Matthijs de Ligt', 'Dutch', 3),
  df('NED', 'Denzel Dumfries', 'Dutch', 22),
  df('NED', 'Daley Blind', 'Dutch', 17),
  df('NED', 'Nathan Aké', 'Dutch', 5),
  df('NED', 'Tyrell Malacia', 'Dutch', 2),
  df('NED', 'Stefan de Vrij', 'Dutch', 6),
  df('NED', 'Jurrien Timber', 'Dutch', 15),
  mf('NED', 'Frenkie de Jong', 'Dutch', 21),
  mf('NED', 'Ryan Gravenberch', 'Dutch', 14),
  mf('NED', 'Teun Koopmeiners', 'Dutch', 8),
  mf('NED', 'Steven Berghuis', 'Dutch', 18),
  mf('NED', 'Davy Klaassen', 'Dutch', 10),
  mf('NED', 'Tijjani Reijnders', 'Dutch', 16),
  mf('NED', 'Xavi Simons', 'Dutch', 7),
  mf('NED', 'Mats Wieffer', 'Dutch', 20),
  fw('NED', 'Memphis Depay', 'Dutch', 10),
  fw('NED', 'Cody Gakpo', 'Dutch', 11),
  fw('NED', 'Wout Weghorst', 'Dutch', 19),
  fw('NED', 'Steven Bergwijn', 'Dutch', 7),
  fw('NED', 'Brian Brobbey', 'Dutch', 9),
  fw('NED', 'Donyell Malen', 'Dutch', 25),

  // ── Group F: Japan ────────────────────────────────────────────────────────
  gk('JPN', 'Shuichi Gonda', 'Japanese', 1),
  gk('JPN', 'Zion Suzuki', 'Japanese', 12),
  gk('JPN', 'Kosei Tani', 'Japanese', 23),
  df('JPN', 'Takehiro Tomiyasu', 'Japanese', 5),
  df('JPN', 'Maya Yoshida', 'Japanese', 22),
  df('JPN', 'Hiroki Sakai', 'Japanese', 2),
  df('JPN', 'Yuto Nagatomo', 'Japanese', 3),
  df('JPN', 'Shogo Taniguchi', 'Japanese', 4),
  df('JPN', 'Ko Itakura', 'Japanese', 6),
  df('JPN', 'Hiroki Ito', 'Japanese', 15),
  df('JPN', 'Miki Yamane', 'Japanese', 16),
  mf('JPN', 'Daichi Kamada', 'Japanese', 10),
  mf('JPN', 'Wataru Endō', 'Japanese', 8),
  mf('JPN', 'Hidemasa Morita', 'Japanese', 14),
  mf('JPN', 'Jūnō Ito', 'Japanese', 17),
  mf('JPN', 'Ao Tanaka', 'Japanese', 13),
  mf('JPN', 'Gaku Shibasaki', 'Japanese', 7),
  mf('JPN', 'Yuki Soma', 'Japanese', 18),
  mf('JPN', 'Genki Haraguchi', 'Japanese', 19),
  fw('JPN', 'Takumi Minamino', 'Japanese', 10),
  fw('JPN', 'Kaoru Mitoma', 'Japanese', 11),
  fw('JPN', 'Ritsu Dōan', 'Japanese', 9),
  fw('JPN', 'Ayase Ueda', 'Japanese', 20),
  fw('JPN', 'Junya Ito', 'Japanese', 21),
  fw('JPN', 'Hinata Kida', 'Japanese', 25),

  // ── Group F: Sweden ───────────────────────────────────────────────────────
  gk('SWE', 'Robin Olsen', 'Swedish', 1),
  gk('SWE', 'Karl-Johan Johnsson', 'Swedish', 12),
  gk('SWE', 'Andreas Linde', 'Swedish', 23),
  df('SWE', 'Victor Lindelöf', 'Swedish', 2),
  df('SWE', 'Pontus Jansson', 'Swedish', 5),
  df('SWE', 'Filip Helander', 'Swedish', 4),
  df('SWE', 'Ludwig Augustinsson', 'Swedish', 3),
  df('SWE', 'Mikael Lustig', 'Swedish', 22),
  df('SWE', 'Emil Krafth', 'Swedish', 6),
  df('SWE', 'Isak Hien', 'Swedish', 15),
  df('SWE', 'Carl Starfelt', 'Swedish', 16),
  mf('SWE', 'Dejan Kulusevski', 'Swedish', 10),
  mf('SWE', 'Emil Forsberg', 'Swedish', 7),
  mf('SWE', 'Albin Ekdal', 'Swedish', 8),
  mf('SWE', 'Mattias Svanberg', 'Swedish', 14),
  mf('SWE', 'Alexander Isak', 'Swedish', 11),
  mf('SWE', 'Samuel Dahl', 'Swedish', 17),
  mf('SWE', 'Jens-Lys Cajuste', 'Swedish', 18),
  mf('SWE', 'Amor Layouni', 'Swedish', 19),
  fw('SWE', 'Viktor Gyökeres', 'Swedish', 9),
  fw('SWE', 'Jordan Larsson', 'Swedish', 11),
  fw('SWE', 'Linus Wahlqvist', 'Swedish', 20),
  fw('SWE', 'Isaac Kiese Thelin', 'Swedish', 21),
  fw('SWE', 'Niclas Eliasson', 'Swedish', 24),
  fw('SWE', 'Pontus Almqvist', 'Swedish', 25),

  // ── Group F: Tunisia ─────────────────────────────────────────────────────
  gk('TUN', 'Aymen Dahmen', 'Tunisian', 1),
  gk('TUN', 'Bechir Ben Said', 'Tunisian', 12),
  gk('TUN', 'Farouk Ben Mustapha', 'Tunisian', 23),
  df('TUN', 'Ali Maaloul', 'Tunisian', 3),
  df('TUN', 'Yassine Meriah', 'Tunisian', 4),
  df('TUN', 'Montassar Talbi', 'Tunisian', 5),
  df('TUN', 'Wajdi Kechrida', 'Tunisian', 2),
  df('TUN', 'Rami Bedoui', 'Tunisian', 6),
  df('TUN', 'Dylan Bronn', 'Tunisian', 15),
  df('TUN', 'Mohamed Amine Ben Hamida', 'Tunisian', 16),
  df('TUN', 'Nader Ghandri', 'Tunisian', 22),
  mf('TUN', 'Ellyes Skhiri', 'Tunisian', 8),
  mf('TUN', 'Wahbi Khazri', 'Tunisian', 10),
  mf('TUN', 'Anis Ben Slimane', 'Tunisian', 14),
  mf('TUN', 'Mohamed Ali Ben Romdhane', 'Tunisian', 7),
  mf('TUN', 'Ghaylane Chaalali', 'Tunisian', 17),
  mf('TUN', 'Hamza Mathlouthi', 'Tunisian', 13),
  mf('TUN', 'Lassad Sassi', 'Tunisian', 18),
  mf('TUN', 'Youssef Belaïli', 'Tunisian', 19),
  fw('TUN', 'Youssef Msakni', 'Tunisian', 11),
  fw('TUN', 'Issam Jebali', 'Tunisian', 9),
  fw('TUN', 'Naïm Sliti', 'Tunisian', 20),
  fw('TUN', 'Taha Yassine Khenissi', 'Tunisian', 21),
  fw('TUN', 'Seifeddine Jaziri', 'Tunisian', 24),
  fw('TUN', 'Mohamed Drager', 'Tunisian', 25),

  // ── Group G: Belgium ─────────────────────────────────────────────────────
  gk('BEL', 'Thibaut Courtois', 'Belgian', 1),
  gk('BEL', 'Koen Casteels', 'Belgian', 12),
  gk('BEL', 'Thomas Kaminski', 'Belgian', 23),
  df('BEL', 'Toby Alderweireld', 'Belgian', 4),
  df('BEL', 'Jan Vertonghen', 'Belgian', 5),
  df('BEL', 'Thomas Meunier', 'Belgian', 2),
  df('BEL', 'Timothy Castagne', 'Belgian', 3),
  df('BEL', 'Zinho Vanheusden', 'Belgian', 6),
  df('BEL', 'Wout Faes', 'Belgian', 15),
  df('BEL', 'Arthur Theate', 'Belgian', 16),
  df('BEL', 'Brandon Mechele', 'Belgian', 22),
  mf('BEL', 'Kevin De Bruyne', 'Belgian', 7),
  mf('BEL', 'Axel Witsel', 'Belgian', 8),
  mf('BEL', 'Yannick Carrasco', 'Belgian', 11),
  mf('BEL', 'Amadou Onana', 'Belgian', 14),
  mf('BEL', 'Leander Dendoncker', 'Belgian', 13),
  mf('BEL', 'Alexis Saelemaekers', 'Belgian', 17),
  mf('BEL', 'Charles De Ketelaere', 'Belgian', 18),
  mf('BEL', 'Johan Bakayoko', 'Belgian', 19),
  fw('BEL', 'Romelu Lukaku', 'Belgian', 9),
  fw('BEL', 'Michy Batshuayi', 'Belgian', 23),
  fw('BEL', 'Jeremy Doku', 'Belgian', 11),
  fw('BEL', 'Lois Openda', 'Belgian', 20),
  fw('BEL', 'Divock Origi', 'Belgian', 21),
  fw('BEL', 'Loïs Openda', 'Belgian', 25),

  // ── Group G: Egypt ────────────────────────────────────────────────────────
  gk('EGY', 'Mohamed El-Shenawy', 'Egyptian', 1),
  gk('EGY', 'Ahmed El-Shenawy', 'Egyptian', 12),
  gk('EGY', 'Mohamed El-Shennawy Jr', 'Egyptian', 23),
  df('EGY', 'Ahmed Hegazi', 'Egyptian', 4),
  df('EGY', 'Mahmoud Hamdy', 'Egyptian', 5),
  df('EGY', 'Mohamed Abdel-Moneim', 'Egyptian', 3),
  df('EGY', 'Ayman Ashraf', 'Egyptian', 2),
  df('EGY', 'Omar Kamal', 'Egyptian', 6),
  df('EGY', 'Akram Tawfik', 'Egyptian', 16),
  df('EGY', 'Zizo', 'Egyptian', 22),
  df('EGY', 'Baher El-Mohamady', 'Egyptian', 15),
  mf('EGY', 'Tarek Hamed', 'Egyptian', 8),
  mf('EGY', 'Mahmoud Trezeguet', 'Egyptian', 10),
  mf('EGY', 'Amr El-Sulayia', 'Egyptian', 14),
  mf('EGY', 'Emam Ashour', 'Egyptian', 7),
  mf('EGY', 'Hamdi Fathi', 'Egyptian', 17),
  mf('EGY', 'Ahmed Sayed Zizou', 'Egyptian', 13),
  mf('EGY', 'Ramadan Sobhi', 'Egyptian', 18),
  mf('EGY', 'Omar Marmoush', 'Egyptian', 19),
  fw('EGY', 'Mohamed Salah', 'Egyptian', 10),
  fw('EGY', 'Mostafa Mohamed', 'Egyptian', 9),
  fw('EGY', 'Marwan Hamdy', 'Egyptian', 11),
  fw('EGY', 'Kahraba', 'Egyptian', 20),
  fw('EGY', 'Ahmed Kouka', 'Egyptian', 21),
  fw('EGY', 'Nasser Maher', 'Egyptian', 25),

  // ── Group G: Iran ─────────────────────────────────────────────────────────
  gk('IRN', 'Alireza Beiranvand', 'Iranian', 1),
  gk('IRN', 'Payam Niazmand', 'Iranian', 12),
  gk('IRN', 'Hossein Hosseini', 'Iranian', 23),
  df('IRN', 'Shoja Khalilzadeh', 'Iranian', 5),
  df('IRN', 'Morteza Pouraliganji', 'Iranian', 3),
  df('IRN', 'Milad Mohammadi', 'Iranian', 4),
  df('IRN', 'Sadegh Moharrami', 'Iranian', 2),
  df('IRN', 'Roozbeh Cheshmi', 'Iranian', 6),
  df('IRN', 'Majid Hosseini', 'Iranian', 16),
  df('IRN', 'Abolfazl Jalali', 'Iranian', 22),
  df('IRN', 'Ehsan Hajsafi', 'Iranian', 15),
  mf('IRN', 'Saeid Ezatolahi', 'Iranian', 8),
  mf('IRN', 'Ahmad Noorollahi', 'Iranian', 14),
  mf('IRN', 'Ali Karimi', 'Iranian', 10),
  mf('IRN', 'Omid Ebrahimi', 'Iranian', 17),
  mf('IRN', 'Vahid Amiri', 'Iranian', 7),
  mf('IRN', 'Alireza Jahanbakhsh', 'Iranian', 11),
  mf('IRN', 'Karim Ansarifard', 'Iranian', 13),
  mf('IRN', 'Mehdi Torabi', 'Iranian', 19),
  fw('IRN', 'Mehdi Taremi', 'Iranian', 9),
  fw('IRN', 'Sardar Azmoun', 'Iranian', 20),
  fw('IRN', 'Allahyar Sayyadmanesh', 'Iranian', 11),
  fw('IRN', 'Karim Azizi', 'Iranian', 21),
  fw('IRN', 'Shahriyar Moghanloo', 'Iranian', 24),
  fw('IRN', 'Siavash Yazdani', 'Iranian', 25),

  // ── Group G: New Zealand ──────────────────────────────────────────────────
  gk('NZL', 'Stefan Marinovic', 'New Zealander', 1),
  gk('NZL', 'Oliver Sail', 'New Zealander', 12),
  gk('NZL', 'Max Crocombe', 'New Zealander', 23),
  df('NZL', 'Winston Reid', 'New Zealander', 5),
  df('NZL', 'Michael Boxall', 'New Zealander', 4),
  df('NZL', 'Nandan Kumar', 'New Zealander', 3),
  df('NZL', 'Tim Payne', 'New Zealander', 2),
  df('NZL', 'Liberato Cacace', 'New Zealander', 16),
  df('NZL', 'Tommy Smith', 'New Zealander', 6),
  df('NZL', 'Cameron Howieson', 'New Zealander', 15),
  df('NZL', 'Dane Ingham', 'New Zealander', 22),
  mf('NZL', 'Joe Bell', 'New Zealander', 8),
  mf('NZL', 'Ryan Thomas', 'New Zealander', 10),
  mf('NZL', 'Elijah Just', 'New Zealander', 14),
  mf('NZL', 'Clayton Lewis', 'New Zealander', 7),
  mf('NZL', 'Kosta Barbarouses', 'New Zealander', 17),
  mf('NZL', 'Louis Fenton', 'New Zealander', 13),
  mf('NZL', 'Callum McCowatt', 'New Zealander', 18),
  mf('NZL', 'Liam McGing', 'New Zealander', 19),
  fw('NZL', 'Chris Wood', 'New Zealander', 9),
  fw('NZL', 'Reon Edwards', 'New Zealander', 11),
  fw('NZL', 'Ben Old', 'New Zealander', 20),
  fw('NZL', 'Marko Stamenic', 'New Zealander', 21),
  fw('NZL', 'Declan Edge', 'New Zealander', 24),
  fw('NZL', 'Matthew Garbett', 'New Zealander', 25),

  // ── Group H: Spain ────────────────────────────────────────────────────────
  gk('ESP', 'Unai Simón', 'Spanish', 23),
  gk('ESP', 'David Raya', 'Spanish', 1),
  gk('ESP', 'Álvaro Fernández', 'Spanish', 13),
  df('ESP', 'Dani Carvajal', 'Spanish', 2),
  df('ESP', 'Pau Cubarsí', 'Spanish', 4),
  df('ESP', 'Laporte', 'Spanish', 14),
  df('ESP', 'Marc Cucurella', 'Spanish', 24),
  df('ESP', 'Alejandro Grimaldo', 'Spanish', 3),
  df('ESP', 'Joselu', 'Spanish', 16),
  df('ESP', 'Nacho Fernández', 'Spanish', 15),
  df('ESP', 'Iñigo Martínez', 'Spanish', 6),
  mf('ESP', 'Rodri', 'Spanish', 16),
  mf('ESP', 'Pedri', 'Spanish', 8),
  mf('ESP', 'Gavi', 'Spanish', 6),
  mf('ESP', 'Fabián Ruiz', 'Spanish', 7),
  mf('ESP', 'Dani Olmo', 'Spanish', 10),
  mf('ESP', 'Mikel Merino', 'Spanish', 20),
  mf('ESP', 'Marcos Llorente', 'Spanish', 14),
  mf('ESP', 'Alejandro Baena', 'Spanish', 22),
  fw('ESP', 'Álvaro Morata', 'Spanish', 9),
  fw('ESP', 'Ansu Fati', 'Spanish', 22),
  fw('ESP', 'Ferran Torres', 'Spanish', 11),
  fw('ESP', 'Nico Williams', 'Spanish', 17),
  fw('ESP', 'Lamine Yamal', 'Spanish', 19),
  fw('ESP', 'Mikel Oyarzabal', 'Spanish', 21),

  // ── Group H: Cape Verde ───────────────────────────────────────────────────
  gk('CPV', 'Vozinha', 'Cape Verdean', 1),
  gk('CPV', 'Elísio Meira', 'Cape Verdean', 12),
  gk('CPV', 'Marcio Rosa', 'Cape Verdean', 23),
  df('CPV', 'Stopira', 'Cape Verdean', 5),
  df('CPV', 'Jeffry Fortes', 'Cape Verdean', 2),
  df('CPV', 'Marcelo Carvalho', 'Cape Verdean', 4),
  df('CPV', 'Kenny Rocha', 'Cape Verdean', 3),
  df('CPV', 'Fali Candé', 'Cape Verdean', 6),
  df('CPV', 'Diney', 'Cape Verdean', 15),
  df('CPV', 'Bryan Teixeira', 'Cape Verdean', 16),
  df('CPV', 'Getterson', 'Cape Verdean', 22),
  mf('CPV', 'Garry Rodrigues', 'Cape Verdean', 10),
  mf('CPV', 'Ryan Mendes', 'Cape Verdean', 7),
  mf('CPV', 'Jamiro Monteiro', 'Cape Verdean', 8),
  mf('CPV', 'Lúcio Antunes', 'Cape Verdean', 14),
  mf('CPV', 'Bebeto Andrade', 'Cape Verdean', 17),
  mf('CPV', 'Steven Fortes', 'Cape Verdean', 13),
  mf('CPV', 'Djaniny', 'Cape Verdean', 18),
  mf('CPV', 'Nilson Tavares', 'Cape Verdean', 19),
  fw('CPV', 'Willy Semedo', 'Cape Verdean', 9),
  fw('CPV', 'Rúben Soares', 'Cape Verdean', 11),
  fw('CPV', 'Carlitos Silva', 'Cape Verdean', 20),
  fw('CPV', 'Kenny Rocha', 'Cape Verdean', 21),
  fw('CPV', 'Tiago Semedo', 'Cape Verdean', 24),
  fw('CPV', 'Bruno Varela', 'Cape Verdean', 25),

  // ── Group H: Saudi Arabia ────────────────────────────────────────────────
  gk('KSA', 'Mohammed Al-Owais', 'Saudi Arabian', 1),
  gk('KSA', 'Fawaz Al-Qarni', 'Saudi Arabian', 12),
  gk('KSA', 'Yasser Al-Mosailem', 'Saudi Arabian', 23),
  df('KSA', 'Ali Al-Bulaihi', 'Saudi Arabian', 5),
  df('KSA', 'Yasser Al-Shahrani', 'Saudi Arabian', 3),
  df('KSA', 'Sultan Al-Ghanam', 'Saudi Arabian', 4),
  df('KSA', 'Abdulhamid', 'Saudi Arabian', 2),
  df('KSA', 'Hassan Al-Tambakti', 'Saudi Arabian', 6),
  df('KSA', 'Saud Abdulhamid', 'Saudi Arabian', 16),
  df('KSA', 'Mohammed Al-Burayk', 'Saudi Arabian', 15),
  df('KSA', 'Hatan Bahbir', 'Saudi Arabian', 22),
  mf('KSA', 'Salman Al-Faraj', 'Saudi Arabian', 8),
  mf('KSA', 'Mohamed Kanno', 'Saudi Arabian', 14),
  mf('KSA', 'Sami Al-Najei', 'Saudi Arabian', 7),
  mf('KSA', 'Ali Al-Hassan', 'Saudi Arabian', 10),
  mf('KSA', 'Abdullah Al-Hamdan', 'Saudi Arabian', 17),
  mf('KSA', 'Hattan Bahbri', 'Saudi Arabian', 13),
  mf('KSA', 'Riyadh Sharahili', 'Saudi Arabian', 18),
  mf('KSA', 'Abdullah Al-Khaibari', 'Saudi Arabian', 19),
  fw('KSA', 'Salem Al-Dawsari', 'Saudi Arabian', 10),
  fw('KSA', 'Firas Al-Buraikan', 'Saudi Arabian', 9),
  fw('KSA', 'Fahad Al-Muwallad', 'Saudi Arabian', 11),
  fw('KSA', 'Ali Al-Ghesheyan', 'Saudi Arabian', 20),
  fw('KSA', 'Muhammed Al-Kuwaykibi', 'Saudi Arabian', 21),
  fw('KSA', 'Nawaf Al-Abid', 'Saudi Arabian', 25),

  // ── Group H: Uruguay ─────────────────────────────────────────────────────
  gk('URU', 'Fernando Muslera', 'Uruguayan', 1),
  gk('URU', 'Sergio Rochet', 'Uruguayan', 12),
  gk('URU', 'Martín Campaña', 'Uruguayan', 23),
  df('URU', 'José Giménez', 'Uruguayan', 2),
  df('URU', 'Diego Godín', 'Uruguayan', 3),
  df('URU', 'Mathías Olivera', 'Uruguayan', 4),
  df('URU', 'Martín Cáceres', 'Uruguayan', 16),
  df('URU', 'Sebastián Coates', 'Uruguayan', 5),
  df('URU', 'Nahitan Nández', 'Uruguayan', 15),
  df('URU', 'Guillermo Varela', 'Uruguayan', 22),
  df('URU', 'Ronald Araújo', 'Uruguayan', 6),
  mf('URU', 'Federico Valverde', 'Uruguayan', 8),
  mf('URU', 'Rodrigo Bentancur', 'Uruguayan', 5),
  mf('URU', 'Manuel Ugarte', 'Uruguayan', 6),
  mf('URU', 'Lucas Torreira', 'Uruguayan', 14),
  mf('URU', 'Diego Lainez', 'Uruguayan', 7),
  mf('URU', 'Matías Vecino', 'Uruguayan', 17),
  mf('URU', 'Maximiliano Araújo', 'Uruguayan', 18),
  mf('URU', 'Facundo Pellistri', 'Uruguayan', 19),
  fw('URU', 'Luis Suárez', 'Uruguayan', 9),
  fw('URU', 'Darwin Núñez', 'Uruguayan', 11),
  fw('URU', 'Facundo Torres', 'Uruguayan', 17),
  fw('URU', 'Brian Rodríguez', 'Uruguayan', 20),
  fw('URU', 'Maxi Gómez', 'Uruguayan', 21),
  fw('URU', 'Agustín Canobbio', 'Uruguayan', 25),

  // ── Group I: France ───────────────────────────────────────────────────────
  gk('FRA', 'Mike Maignan', 'French', 16),
  gk('FRA', 'Alphonse Areola', 'French', 23),
  gk('FRA', 'Brice Samba', 'French', 1),
  df('FRA', 'Jules Koundé', 'French', 5),
  df('FRA', 'Raphaël Varane', 'French', 4),
  df('FRA', 'Dayot Upamecano', 'French', 15),
  df('FRA', 'Theo Hernandez', 'French', 22),
  df('FRA', 'Lucas Digne', 'French', 3),
  df('FRA', 'Benjamin Pavard', 'French', 2),
  df('FRA', 'William Saliba', 'French', 17),
  df('FRA', 'Jonathan Clauss', 'French', 14),
  mf('FRA', "N'Golo Kante", 'French', 13),
  mf('FRA', 'Aurélien Tchouaméni', 'French', 8),
  mf('FRA', 'Antoine Griezmann', 'French', 7),
  mf('FRA', 'Adrien Rabiot', 'French', 14),
  mf('FRA', 'Eduardo Camavinga', 'French', 18),
  mf('FRA', 'Youssouf Fofana', 'French', 19),
  mf('FRA', 'Matteo Guendouzi', 'French', 20),
  mf('FRA', 'Warren Zaïre-Emery', 'French', 21),
  fw('FRA', 'Kylian Mbappé', 'French', 10),
  fw('FRA', 'Ousmane Dembélé', 'French', 11),
  fw('FRA', 'Marcus Thuram', 'French', 9),
  fw('FRA', 'Randal Kolo Muani', 'French', 12),
  fw('FRA', 'Bradley Barcola', 'French', 24),
  fw('FRA', 'Kingsley Coman', 'French', 25),

  // ── Group I: Senegal ──────────────────────────────────────────────────────
  gk('SEN', 'Édouard Mendy', 'Senegalese', 16),
  gk('SEN', 'Seny Dieng', 'Senegalese', 1),
  gk('SEN', 'Alfred Gomis', 'Senegalese', 23),
  df('SEN', 'Kalidou Koulibaly', 'Senegalese', 3),
  df('SEN', 'Abdou Diallo', 'Senegalese', 5),
  df('SEN', 'Saliou Ciss', 'Senegalese', 22),
  df('SEN', 'Pape Abou Cissé', 'Senegalese', 4),
  df('SEN', 'Formose Mendy', 'Senegalese', 15),
  df('SEN', 'Fodé Ballo-Touré', 'Senegalese', 16),
  df('SEN', 'Bouna Sarr', 'Senegalese', 2),
  df('SEN', 'Ibrahima Mbaye', 'Senegalese', 6),
  mf('SEN', 'Cheikhou Kouyaté', 'Senegalese', 8),
  mf('SEN', 'Idrissa Gueye', 'Senegalese', 14),
  mf('SEN', 'Nampalys Mendy', 'Senegalese', 10),
  mf('SEN', 'Mamadou Loum', 'Senegalese', 17),
  mf('SEN', 'Pape Matar Sarr', 'Senegalese', 13),
  mf('SEN', 'Krepin Diatta', 'Senegalese', 7),
  mf('SEN', 'Lamine Camara', 'Senegalese', 18),
  mf('SEN', 'Pathé Ciss', 'Senegalese', 19),
  fw('SEN', 'Sadio Mané', 'Senegalese', 10),
  fw('SEN', 'Ismaila Sarr', 'Senegalese', 9),
  fw('SEN', 'Bamba Dieng', 'Senegalese', 11),
  fw('SEN', 'Nicolas Jackson', 'Senegalese', 20),
  fw('SEN', 'Habib Diallo', 'Senegalese', 21),
  fw('SEN', 'Abdallah Sima', 'Senegalese', 25),

  // ── Group I: Iraq ────────────────────────────────────────────────────────
  gk('IRQ', 'Jalal Hassan', 'Iraqi', 1),
  gk('IRQ', 'Mohammed Hameed', 'Iraqi', 12),
  gk('IRQ', 'Ahmad Basim', 'Iraqi', 23),
  df('IRQ', 'Ali Adnan', 'Iraqi', 3),
  df('IRQ', 'Saad Abdul-Amir', 'Iraqi', 4),
  df('IRQ', 'Hussein Ali', 'Iraqi', 5),
  df('IRQ', 'Ahmed Ibrahim', 'Iraqi', 2),
  df('IRQ', 'Mohammed Hamid', 'Iraqi', 6),
  df('IRQ', 'Rebin Sulaka', 'Iraqi', 15),
  df('IRQ', 'Safa Haji', 'Iraqi', 16),
  df('IRQ', 'Mustafa Nadhim', 'Iraqi', 22),
  mf('IRQ', 'Amjad Attwan', 'Iraqi', 8),
  mf('IRQ', 'Aziz Khyoon', 'Iraqi', 10),
  mf('IRQ', 'Nashat Akram', 'Iraqi', 14),
  mf('IRQ', 'Alaa Abdul-Zahra', 'Iraqi', 7),
  mf('IRQ', 'Osama Rashid', 'Iraqi', 17),
  mf('IRQ', 'Bashar Resan', 'Iraqi', 13),
  mf('IRQ', 'Saif Ghalib', 'Iraqi', 18),
  mf('IRQ', 'Hammadi Ahmad', 'Iraqi', 19),
  fw('IRQ', 'Mohanad Ali', 'Iraqi', 9),
  fw('IRQ', 'Ayman Hussein', 'Iraqi', 11),
  fw('IRQ', 'Aymen Husein', 'Iraqi', 20),
  fw('IRQ', 'Karrar Jassim', 'Iraqi', 21),
  fw('IRQ', 'Laith Husain', 'Iraqi', 24),
  fw('IRQ', 'Zaid Tahseen', 'Iraqi', 25),

  // ── Group I: Norway ───────────────────────────────────────────────────────
  gk('NOR', 'Ørjan Nyland', 'Norwegian', 1),
  gk('NOR', 'Rune Jarstein', 'Norwegian', 12),
  gk('NOR', 'Matz Sels', 'Norwegian', 23),
  df('NOR', 'Kristoffer Ajer', 'Norwegian', 5),
  df('NOR', 'Stefan Strandberg', 'Norwegian', 4),
  df('NOR', 'Birger Meling', 'Norwegian', 3),
  df('NOR', 'Omar Elabdellaoui', 'Norwegian', 2),
  df('NOR', 'Stian Gregersen', 'Norwegian', 6),
  df('NOR', 'Leo Østigård', 'Norwegian', 15),
  df('NOR', 'Julian Ryerson', 'Norwegian', 22),
  df('NOR', 'Mats Møller Dæhli', 'Norwegian', 16),
  mf('NOR', 'Martin Ødegaard', 'Norwegian', 10),
  mf('NOR', 'Sander Berge', 'Norwegian', 8),
  mf('NOR', 'Mathias Normann', 'Norwegian', 14),
  mf('NOR', 'Fredrik Aursnes', 'Norwegian', 7),
  mf('NOR', 'Markus Henriksen', 'Norwegian', 17),
  mf('NOR', 'Patrick Berg', 'Norwegian', 13),
  mf('NOR', 'Kristian Thorstvedt', 'Norwegian', 18),
  mf('NOR', 'Mathis Bolly', 'Norwegian', 19),
  fw('NOR', 'Erling Haaland', 'Norwegian', 9),
  fw('NOR', 'Joshua King', 'Norwegian', 11),
  fw('NOR', 'Alexander Sørloth', 'Norwegian', 20),
  fw('NOR', 'Ola Brynhildsen', 'Norwegian', 21),
  fw('NOR', 'Mohamed Elyounoussi', 'Norwegian', 24),
  fw('NOR', 'Jørgen Strand Larsen', 'Norwegian', 25),

  // ── Group J: Argentina ───────────────────────────────────────────────────
  gk('ARG', 'Emiliano Martínez', 'Argentine', 23),
  gk('ARG', 'Juan Musso', 'Argentine', 12),
  gk('ARG', 'Gerónimo Rulli', 'Argentine', 1),
  df('ARG', 'Nahuel Molina', 'Argentine', 26),
  df('ARG', 'Cristian Romero', 'Argentine', 13),
  df('ARG', 'Lisandro Martínez', 'Argentine', 14),
  df('ARG', 'Nicolás Tagliafico', 'Argentine', 3),
  df('ARG', 'Germán Pezzella', 'Argentine', 6),
  df('ARG', 'Gonzalo Montiel', 'Argentine', 22),
  df('ARG', 'Marcos Acuña', 'Argentine', 8),
  df('ARG', 'Nicolás Otamendi', 'Argentine', 19),
  mf('ARG', 'Rodrigo De Paul', 'Argentine', 7),
  mf('ARG', 'Enzo Fernández', 'Argentine', 24),
  mf('ARG', 'Alexis Mac Allister', 'Argentine', 20),
  mf('ARG', 'Leandro Paredes', 'Argentine', 5),
  mf('ARG', 'Exequiel Palacios', 'Argentine', 14),
  mf('ARG', 'Guido Rodríguez', 'Argentine', 18),
  mf('ARG', 'Giovani Lo Celso', 'Argentine', 16),
  mf('ARG', 'Alejandro Garnacho', 'Argentine', 15),
  fw('ARG', 'Lionel Messi', 'Argentine', 10),
  fw('ARG', 'Julián Álvarez', 'Argentine', 9),
  fw('ARG', 'Ángel Di María', 'Argentine', 11),
  fw('ARG', 'Lautaro Martínez', 'Argentine', 22),
  fw('ARG', 'Paulo Dybala', 'Argentine', 21),
  fw('ARG', 'Nicolás González', 'Argentine', 17),

  // ── Group J: Algeria ──────────────────────────────────────────────────────
  gk('ALG', 'Rais M. Bolhi', 'Algerian', 1),
  gk('ALG', 'Alexandre Oukidja', 'Algerian', 12),
  gk('ALG', 'Youssef Benali', 'Algerian', 23),
  df('ALG', 'Aissa Mandi', 'Algerian', 5),
  df('ALG', 'Ramy Bensebaini', 'Algerian', 3),
  df('ALG', 'Mehdi Tahrat', 'Algerian', 4),
  df('ALG', 'Hossem Aouar', 'Algerian', 6),
  df('ALG', 'Youcef Atal', 'Algerian', 2),
  df('ALG', 'Djamel Benlamri', 'Algerian', 15),
  df('ALG', 'Sofiane Bendebka', 'Algerian', 16),
  df('ALG', 'Abdelkader Bedrane', 'Algerian', 22),
  mf('ALG', 'Adlène Guedioura', 'Algerian', 8),
  mf('ALG', 'Sofiane Feghouli', 'Algerian', 10),
  mf('ALG', 'Nabil Bentaleb', 'Algerian', 14),
  mf('ALG', 'Ismaël Bennacer', 'Algerian', 7),
  mf('ALG', 'Mehdi Zeffane', 'Algerian', 17),
  mf('ALG', 'Said Benrahma', 'Algerian', 13),
  mf('ALG', 'Yacine Brahimi', 'Algerian', 18),
  mf('ALG', 'Billal Brahimi', 'Algerian', 19),
  fw('ALG', 'Riyad Mahrez', 'Algerian', 7),
  fw('ALG', 'Andy Delort', 'Algerian', 9),
  fw('ALG', 'Islam Slimani', 'Algerian', 11),
  fw('ALG', 'Baghdad Bounedjah', 'Algerian', 20),
  fw('ALG', 'Yacine Adli', 'Algerian', 21),
  fw('ALG', 'Adam Zorgane', 'Algerian', 25),

  // ── Group J: Austria ──────────────────────────────────────────────────────
  gk('AUT', 'Daniel Bachmann', 'Austrian', 1),
  gk('AUT', 'Patrick Pentz', 'Austrian', 12),
  gk('AUT', 'Alexander Schlager', 'Austrian', 23),
  df('AUT', 'David Alaba', 'Austrian', 6),
  df('AUT', 'Phillipp Lienhart', 'Austrian', 4),
  df('AUT', 'Stefan Posch', 'Austrian', 5),
  df('AUT', 'Andreas Weimann', 'Austrian', 2),
  df('AUT', 'Maximilian Wöber', 'Austrian', 3),
  df('AUT', 'Gernot Trauner', 'Austrian', 15),
  df('AUT', 'Kevin Danso', 'Austrian', 16),
  df('AUT', 'Flavius Daniliuc', 'Austrian', 22),
  mf('AUT', 'Marcel Sabitzer', 'Austrian', 8),
  mf('AUT', 'Florian Grillitsch', 'Austrian', 14),
  mf('AUT', 'Nicolas Seiwald', 'Austrian', 7),
  mf('AUT', 'Konrad Laimer', 'Austrian', 13),
  mf('AUT', 'Patrick Wimmer', 'Austrian', 17),
  mf('AUT', 'Florian Kainz', 'Austrian', 18),
  mf('AUT', 'Christoph Baumgartner', 'Austrian', 10),
  mf('AUT', 'Romano Schmid', 'Austrian', 19),
  fw('AUT', 'Marko Arnautovic', 'Austrian', 9),
  fw('AUT', 'Michael Gregoritsch', 'Austrian', 11),
  fw('AUT', 'Sasa Kalajdzic', 'Austrian', 20),
  fw('AUT', 'Patrick Wimmer', 'Austrian', 21),
  fw('AUT', 'Karim Adeyemi', 'Austrian', 24),
  fw('AUT', 'Guido Burgstaller', 'Austrian', 25),

  // ── Group J: Jordan ───────────────────────────────────────────────────────
  gk('JOR', 'Amer Shafi', 'Jordanian', 1),
  gk('JOR', 'Mohammad Abu Alros', 'Jordanian', 12),
  gk('JOR', 'Yazeed Abo Laila', 'Jordanian', 23),
  df('JOR', 'Osamah Rashid', 'Jordanian', 5),
  df('JOR', 'Baher Al-Rawabdeh', 'Jordanian', 4),
  df('JOR', 'Musa Suleiman', 'Jordanian', 3),
  df('JOR', 'Mohammed Hasan', 'Jordanian', 2),
  df('JOR', 'Montaser Ibrahim', 'Jordanian', 6),
  df('JOR', 'Salem Al-Ajalin', 'Jordanian', 15),
  df('JOR', 'Ahmad Hasan', 'Jordanian', 16),
  df('JOR', 'Ahmad Ibrahim', 'Jordanian', 22),
  mf('JOR', 'Ahmad Salam', 'Jordanian', 8),
  mf('JOR', 'Baha Faisal', 'Jordanian', 10),
  mf('JOR', 'Mousa Al-Taamari', 'Jordanian', 7),
  mf('JOR', 'Yazan Al-Naimat', 'Jordanian', 14),
  mf('JOR', 'Hamzah Hasan', 'Jordanian', 17),
  mf('JOR', 'Ahmad Abueid', 'Jordanian', 13),
  mf('JOR', 'Khaled Doumani', 'Jordanian', 18),
  mf('JOR', 'Mohammad Abu Zema', 'Jordanian', 19),
  fw('JOR', 'Yousef Al-Rawabdeh', 'Jordanian', 9),
  fw('JOR', 'Ahmad Al-Ali', 'Jordanian', 11),
  fw('JOR', 'Mutaz Nassar', 'Jordanian', 20),
  fw('JOR', 'Ramzi Salehi', 'Jordanian', 21),
  fw('JOR', 'Firas Ibrahim', 'Jordanian', 24),
  fw('JOR', 'Hamzah Ibrahim', 'Jordanian', 25),

  // ── Group K: Portugal ────────────────────────────────────────────────────
  gk('POR', 'Diogo Costa', 'Portuguese', 1),
  gk('POR', 'Rui Patrício', 'Portuguese', 12),
  gk('POR', 'José Sá', 'Portuguese', 23),
  df('POR', 'João Cancelo', 'Portuguese', 20),
  df('POR', 'Rúben Dias', 'Portuguese', 4),
  df('POR', 'Pepe', 'Portuguese', 3),
  df('POR', 'Nuno Mendes', 'Portuguese', 22),
  df('POR', 'Danilo Pereira', 'Portuguese', 14),
  df('POR', 'Gonçalo Inácio', 'Portuguese', 5),
  df('POR', 'Diogo Dalot', 'Portuguese', 2),
  df('POR', 'Tiago Djaló', 'Portuguese', 6),
  mf('POR', 'Bruno Fernandes', 'Portuguese', 8),
  mf('POR', 'Bernardo Silva', 'Portuguese', 10),
  mf('POR', 'João Palhinha', 'Portuguese', 14),
  mf('POR', 'Vitinha', 'Portuguese', 16),
  mf('POR', 'Rúben Neves', 'Portuguese', 15),
  mf('POR', 'William Carvalho', 'Portuguese', 17),
  mf('POR', 'Otávio', 'Portuguese', 13),
  mf('POR', 'João Neves', 'Portuguese', 18),
  fw('POR', 'Cristiano Ronaldo', 'Portuguese', 7),
  fw('POR', 'Rafael Leão', 'Portuguese', 11),
  fw('POR', 'Pedro Neto', 'Portuguese', 7),
  fw('POR', 'Gonçalo Ramos', 'Portuguese', 9),
  fw('POR', 'João Félix', 'Portuguese', 21),
  fw('POR', 'Francisco Conceição', 'Portuguese', 19),

  // ── Group K: DR Congo ────────────────────────────────────────────────────
  gk('COD', 'Joël Kiassumbua', 'Congolese', 1),
  gk('COD', 'Robert Kidiaba', 'Congolese', 12),
  gk('COD', 'Lionel Mpasi', 'Congolese', 23),
  df('COD', 'Chancel Mbemba', 'Congolese', 4),
  df('COD', 'Christian Luyindama', 'Congolese', 5),
  df('COD', 'Marcel Tisserand', 'Congolese', 3),
  df('COD', 'Dodi Lukébakio', 'Congolese', 2),
  df('COD', 'Gaël Kakuta', 'Congolese', 6),
  df('COD', 'Theo Bongonda', 'Congolese', 16),
  df('COD', 'Yannick Bolasie', 'Congolese', 22),
  df('COD', 'Elia Meschack', 'Congolese', 15),
  mf('COD', 'Yannick Ferreira-Carrasco', 'Congolese', 8),
  mf('COD', 'Ced Bakambu', 'Congolese', 10),
  mf('COD', 'Neeskens Kebano', 'Congolese', 14),
  mf('COD', 'Jonathan Bolingi', 'Congolese', 7),
  mf('COD', 'Silas Mvumpa', 'Congolese', 17),
  mf('COD', 'Steven Mounie', 'Congolese', 13),
  mf('COD', 'Donavon Lonwijk', 'Congolese', 18),
  mf('COD', 'Firmin Mubele', 'Congolese', 19),
  fw('COD', 'Cédric Bakambu', 'Congolese', 9),
  fw('COD', 'Gael Kakuta', 'Congolese', 11),
  fw('COD', 'Emmanuel Lebo', 'Congolese', 20),
  fw('COD', 'Joris Kayembe', 'Congolese', 21),
  fw('COD', 'Paul-José Mpoku', 'Congolese', 24),
  fw('COD', 'Fiston Mayele', 'Congolese', 25),

  // ── Group K: Uzbekistan ───────────────────────────────────────────────────
  gk('UZB', 'Eldorbek Sobirov', 'Uzbek', 1),
  gk('UZB', 'Abdusalom Abdullayev', 'Uzbek', 12),
  gk('UZB', 'Timur Jurayev', 'Uzbek', 23),
  df('UZB', 'Sherzod Nasimov', 'Uzbek', 5),
  df('UZB', 'Akbar Tursunov', 'Uzbek', 4),
  df('UZB', 'Doston Khamdamov', 'Uzbek', 3),
  df('UZB', 'Otabek Shukurov', 'Uzbek', 2),
  df('UZB', 'Bobur Abdixoliqov', 'Uzbek', 6),
  df('UZB', 'Nodir Sultonov', 'Uzbek', 15),
  df('UZB', 'Jasur Yaxshiboyev', 'Uzbek', 16),
  df('UZB', 'Dilshod Nematov', 'Uzbek', 22),
  mf('UZB', 'Jaloliddin Masharipov', 'Uzbek', 8),
  mf('UZB', 'Dostonbek Khamdamov', 'Uzbek', 10),
  mf('UZB', 'Oybek Bozorov', 'Uzbek', 14),
  mf('UZB', 'Otabek Fayzullayev', 'Uzbek', 7),
  mf('UZB', 'Abbosbek Fayzullayev', 'Uzbek', 17),
  mf('UZB', 'Behruzbek Ismoilov', 'Uzbek', 13),
  mf('UZB', 'Khojiakbar Alijonov', 'Uzbek', 18),
  mf('UZB', 'Asilbek Komilov', 'Uzbek', 19),
  fw('UZB', 'Eldor Shomurodov', 'Uzbek', 9),
  fw('UZB', 'Shokhrukh Komilov', 'Uzbek', 11),
  fw('UZB', 'Jasur Narzullayev', 'Uzbek', 20),
  fw('UZB', 'Umid Omonov', 'Uzbek', 21),
  fw('UZB', 'Davron Mirzayev', 'Uzbek', 24),
  fw('UZB', 'Temur Jalolov', 'Uzbek', 25),

  // ── Group K: Colombia ────────────────────────────────────────────────────
  gk('COL', 'David Ospina', 'Colombian', 1),
  gk('COL', 'Camilo Vargas', 'Colombian', 12),
  gk('COL', 'Álvaro Montero', 'Colombian', 23),
  df('COL', 'Dávinson Sánchez', 'Colombian', 2),
  df('COL', 'Yerry Mina', 'Colombian', 13),
  df('COL', 'Jhon Lucumí', 'Colombian', 4),
  df('COL', 'Johan Mojica', 'Colombian', 3),
  df('COL', 'Santiago Arias', 'Colombian', 22),
  df('COL', 'Carlos Cuesta', 'Colombian', 5),
  df('COL', 'Stefan Medina', 'Colombian', 15),
  df('COL', 'William Tesillo', 'Colombian', 16),
  mf('COL', 'James Rodríguez', 'Colombian', 10),
  mf('COL', 'Wilmar Barrios', 'Colombian', 8),
  mf('COL', 'Mateus Uribe', 'Colombian', 14),
  mf('COL', 'Juan Cuadrado', 'Colombian', 7),
  mf('COL', 'Richard Ríos', 'Colombian', 17),
  mf('COL', 'Jefferson Lerma', 'Colombian', 13),
  mf('COL', 'Daniel Muñoz', 'Colombian', 18),
  mf('COL', 'Jhon Arias', 'Colombian', 19),
  fw('COL', 'Luis Díaz', 'Colombian', 7),
  fw('COL', 'Rafael Santos Borré', 'Colombian', 9),
  fw('COL', 'Duván Zapata', 'Colombian', 11),
  fw('COL', 'Jhon Córdoba', 'Colombian', 20),
  fw('COL', 'Miguel Ángel Borja', 'Colombian', 21),
  fw('COL', 'Alfredo Morelos', 'Colombian', 25),

  // ── Group L: England ─────────────────────────────────────────────────────
  gk('ENG', 'Jordan Pickford', 'English', 1),
  gk('ENG', 'Nick Pope', 'English', 12),
  gk('ENG', 'Aaron Ramsdale', 'English', 23),
  df('ENG', 'Trent Alexander-Arnold', 'English', 2),
  df('ENG', 'John Stones', 'English', 5),
  df('ENG', 'Harry Maguire', 'English', 6),
  df('ENG', 'Luke Shaw', 'English', 3),
  df('ENG', 'Kieran Trippier', 'English', 22),
  df('ENG', 'Marc Guehi', 'English', 4),
  df('ENG', 'Ben Chilwell', 'English', 15),
  df('ENG', 'Reece James', 'English', 16),
  mf('ENG', 'Jude Bellingham', 'English', 10),
  mf('ENG', 'Declan Rice', 'English', 4),
  mf('ENG', 'Phil Foden', 'English', 11),
  mf('ENG', 'Jordan Henderson', 'English', 14),
  mf('ENG', 'Conor Gallagher', 'English', 17),
  mf('ENG', 'Kobbie Mainoo', 'English', 20),
  mf('ENG', 'Curtis Jones', 'English', 18),
  mf('ENG', 'Adam Wharton', 'English', 19),
  fw('ENG', 'Harry Kane', 'English', 9),
  fw('ENG', 'Bukayo Saka', 'English', 7),
  fw('ENG', 'Marcus Rashford', 'English', 11),
  fw('ENG', 'Raheem Sterling', 'English', 7),
  fw('ENG', 'Ivan Toney', 'English', 21),
  fw('ENG', 'Jarrod Bowen', 'English', 25),

  // ── Group L: Croatia ─────────────────────────────────────────────────────
  gk('CRO', 'Dominik Livaković', 'Croatian', 1),
  gk('CRO', 'Ivica Ivušić', 'Croatian', 12),
  gk('CRO', 'Lovre Kalinić', 'Croatian', 23),
  df('CRO', 'Josip Juranović', 'Croatian', 2),
  df('CRO', 'Domagoj Vida', 'Croatian', 21),
  df('CRO', 'Joško Gvardiol', 'Croatian', 24),
  df('CRO', 'Borna Sosa', 'Croatian', 3),
  df('CRO', 'Dejan Lovren', 'Croatian', 6),
  df('CRO', 'Martin Erlić', 'Croatian', 5),
  df('CRO', 'Borna Barisic', 'Croatian', 22),
  df('CRO', 'Josip Stanišić', 'Croatian', 15),
  mf('CRO', 'Luka Modrić', 'Croatian', 10),
  mf('CRO', 'Mateo Kovačić', 'Croatian', 8),
  mf('CRO', 'Marcelo Brozović', 'Croatian', 11),
  mf('CRO', 'Milan Badelj', 'Croatian', 14),
  mf('CRO', 'Mario Pašalić', 'Croatian', 7),
  mf('CRO', 'Nikola Vlašić', 'Croatian', 13),
  mf('CRO', 'Ivan Perišić', 'Croatian', 4),
  mf('CRO', 'Lovro Majer', 'Croatian', 19),
  fw('CRO', 'Andrej Kramarić', 'Croatian', 9),
  fw('CRO', 'Bruno Petković', 'Croatian', 16),
  fw('CRO', 'Marko Livaja', 'Croatian', 17),
  fw('CRO', 'Ante Budimir', 'Croatian', 20),
  fw('CRO', 'Mislav Oršić', 'Croatian', 18),
  fw('CRO', 'Duje Ćaleta-Car', 'Croatian', 25),

  // ── Group L: Ghana ────────────────────────────────────────────────────────
  gk('GHA', 'Lawrence Ati-Zigi', 'Ghanaian', 1),
  gk('GHA', 'Richard Ofori', 'Ghanaian', 12),
  gk('GHA', 'Manaf Nurudeen', 'Ghanaian', 23),
  df('GHA', 'Daniel Amartey', 'Ghanaian', 5),
  df('GHA', 'Alexander Djiku', 'Ghanaian', 4),
  df('GHA', 'Gideon Mensah', 'Ghanaian', 3),
  df('GHA', 'Tariq Lamptey', 'Ghanaian', 2),
  df('GHA', 'Denis Odoi', 'Ghanaian', 6),
  df('GHA', 'Andy Yiadom', 'Ghanaian', 22),
  df('GHA', 'Baba Rahman', 'Ghanaian', 15),
  df('GHA', 'Joseph Aidoo', 'Ghanaian', 16),
  mf('GHA', 'Thomas Partey', 'Ghanaian', 5),
  mf('GHA', 'André Ayew', 'Ghanaian', 10),
  mf('GHA', 'Iddrisu Baba', 'Ghanaian', 8),
  mf('GHA', 'Daniel-Kofi Kyereh', 'Ghanaian', 14),
  mf('GHA', 'Elisha Owusu', 'Ghanaian', 17),
  mf('GHA', 'Emmanuel Lomotey', 'Ghanaian', 7),
  mf('GHA', 'Salis Abdul Samed', 'Ghanaian', 13),
  mf('GHA', 'Osman Bukari', 'Ghanaian', 19),
  fw('GHA', 'Jordan Ayew', 'Ghanaian', 11),
  fw('GHA', 'Mohammed Kudus', 'Ghanaian', 9),
  fw('GHA', 'Inaki Williams', 'Ghanaian', 20),
  fw('GHA', 'Kamaldeen Sulemana', 'Ghanaian', 21),
  fw('GHA', 'Felix Afena-Gyan', 'Ghanaian', 24),
  fw('GHA', 'Ernest Nuamah', 'Ghanaian', 25),

  // ── Group L: Panama ───────────────────────────────────────────────────────
  gk('PAN', 'Luis Mejía', 'Panamanian', 1),
  gk('PAN', 'Orlando Mosquera', 'Panamanian', 12),
  gk('PAN', 'Jaime Penedo', 'Panamanian', 23),
  df('PAN', 'Fidel Escobar', 'Panamanian', 5),
  df('PAN', 'Eric Davis', 'Panamanian', 4),
  df('PAN', 'Harold Cummings', 'Panamanian', 3),
  df('PAN', 'Michael Murillo', 'Panamanian', 22),
  df('PAN', 'Edgar Yoel', 'Panamanian', 2),
  df('PAN', 'Andrés Andrade', 'Panamanian', 6),
  df('PAN', 'Ernesto Walker', 'Panamanian', 16),
  df('PAN', 'Martín Rodríguez', 'Panamanian', 15),
  mf('PAN', 'Aníbal Godoy', 'Panamanian', 8),
  mf('PAN', 'Adalberto Carrasquilla', 'Panamanian', 10),
  mf('PAN', 'Alberto Quintero', 'Panamanian', 7),
  mf('PAN', 'Édgar Bárcenas', 'Panamanian', 14),
  mf('PAN', 'Amir Murillo', 'Panamanian', 17),
  mf('PAN', 'Ismael Díaz', 'Panamanian', 13),
  mf('PAN', 'Azmahar Ariano', 'Panamanian', 18),
  mf('PAN', 'Jovani Welch', 'Panamanian', 19),
  fw('PAN', 'Cecilio Waterman', 'Panamanian', 9),
  fw('PAN', 'Rolando Blackburn', 'Panamanian', 11),
  fw('PAN', 'Gabriel Torres', 'Panamanian', 20),
  fw('PAN', 'José Luis Rodríguez', 'Panamanian', 21),
  fw('PAN', 'Omar Browne', 'Panamanian', 24),
  fw('PAN', 'Víctor Ángulo', 'Panamanian', 25),
];
