export interface PslClub {
  name: string;
  slug: string;
  shortName: string;
  country: string;
  externalId: string;
  primaryColour: string;
  secondaryColour: string;
  city: string;
  venueExternalId: string;
  venueName: string;
  venueCapacity: number;
}

export const PSL_CLUBS: PslClub[] = [
  {
    name: 'Mamelodi Sundowns',
    slug: 'mamelodi-sundowns',
    shortName: 'Sundowns',
    country: 'South Africa',
    externalId: 'psl-mamelodi-sundowns',
    primaryColour: '#FFD700',
    secondaryColour: '#003DA5',
    city: 'Pretoria',
    venueExternalId: 'psl-venue-loftus',
    venueName: 'Loftus Versfeld Stadium',
    venueCapacity: 51762,
  },
  {
    name: 'Kaizer Chiefs',
    slug: 'kaizer-chiefs',
    shortName: 'Chiefs',
    country: 'South Africa',
    externalId: 'psl-kaizer-chiefs',
    primaryColour: '#FFC72C',
    secondaryColour: '#000000',
    city: 'Johannesburg',
    venueExternalId: 'psl-venue-fnb',
    venueName: 'FNB Stadium',
    venueCapacity: 94736,
  },
  {
    name: 'Orlando Pirates',
    slug: 'orlando-pirates',
    shortName: 'Pirates',
    country: 'South Africa',
    externalId: 'psl-orlando-pirates',
    primaryColour: '#000000',
    secondaryColour: '#FFFFFF',
    city: 'Johannesburg',
    venueExternalId: 'psl-venue-orlando',
    venueName: 'Orlando Stadium',
    venueCapacity: 40000,
  },
  {
    name: 'SuperSport United',
    slug: 'supersport-united',
    shortName: 'SuperSport',
    country: 'South Africa',
    externalId: 'psl-supersport-united',
    primaryColour: '#0070C0',
    secondaryColour: '#FFFFFF',
    city: 'Pretoria',
    venueExternalId: 'psl-venue-lucas-moripe',
    venueName: 'Lucas Moripe Stadium',
    venueCapacity: 40000,
  },
  {
    name: 'Cape Town City',
    slug: 'cape-town-city',
    shortName: 'CT City',
    country: 'South Africa',
    externalId: 'psl-cape-town-city',
    primaryColour: '#0082CA',
    secondaryColour: '#FFFFFF',
    city: 'Cape Town',
    venueExternalId: 'psl-venue-dhl-newlands',
    venueName: 'DHL Newlands',
    venueCapacity: 51900,
  },
  {
    name: 'Stellenbosch FC',
    slug: 'stellenbosch-fc',
    shortName: 'Stellies',
    country: 'South Africa',
    externalId: 'psl-stellenbosch-fc',
    primaryColour: '#A50034',
    secondaryColour: '#FFFFFF',
    city: 'Stellenbosch',
    venueExternalId: 'psl-venue-danie-craven',
    venueName: 'Danie Craven Stadium',
    venueCapacity: 10000,
  },
  {
    name: 'TS Galaxy',
    slug: 'ts-galaxy',
    shortName: 'Galaxy',
    country: 'South Africa',
    externalId: 'psl-ts-galaxy',
    primaryColour: '#E30613',
    secondaryColour: '#000000',
    city: 'Thulamahashe',
    venueExternalId: 'psl-venue-mbombela',
    venueName: 'Mbombela Stadium',
    venueCapacity: 46000,
  },
  {
    name: 'Sekhukhune United',
    slug: 'sekhukhune-united',
    shortName: 'Sekhukhune',
    country: 'South Africa',
    externalId: 'psl-sekhukhune-united',
    primaryColour: '#D01515',
    secondaryColour: '#FFFFFF',
    city: 'Polokwane',
    venueExternalId: 'psl-venue-peter-mokaba',
    venueName: 'Peter Mokaba Stadium',
    venueCapacity: 40929,
  },
  {
    name: 'AmaZulu FC',
    slug: 'amazulu-fc',
    shortName: 'AmaZulu',
    country: 'South Africa',
    externalId: 'psl-amazulu-fc',
    primaryColour: '#000000',
    secondaryColour: '#FFD700',
    city: 'Durban',
    venueExternalId: 'psl-venue-moses-mabhida',
    venueName: 'Moses Mabhida Stadium',
    venueCapacity: 54000,
  },
  {
    name: 'Golden Arrows',
    slug: 'golden-arrows',
    shortName: 'Arrows',
    country: 'South Africa',
    externalId: 'psl-golden-arrows',
    primaryColour: '#FFD700',
    secondaryColour: '#000000',
    city: 'Durban',
    venueExternalId: 'psl-venue-princess-magogo',
    venueName: 'Princess Magogo Stadium',
    venueCapacity: 10000,
  },
  {
    name: 'Chippa United',
    slug: 'chippa-united',
    shortName: 'Chippa',
    country: 'South Africa',
    externalId: 'psl-chippa-united',
    primaryColour: '#FF6600',
    secondaryColour: '#000000',
    city: 'Gqeberha',
    venueExternalId: 'psl-venue-nelson-mandela-bay',
    venueName: 'Nelson Mandela Bay Stadium',
    venueCapacity: 46000,
  },
  {
    name: 'Polokwane City',
    slug: 'polokwane-city',
    shortName: 'Polokwane',
    country: 'South Africa',
    externalId: 'psl-polokwane-city',
    primaryColour: '#006400',
    secondaryColour: '#FFFFFF',
    city: 'Polokwane',
    venueExternalId: 'psl-venue-peter-mokaba',
    venueName: 'Peter Mokaba Stadium',
    venueCapacity: 40929,
  },
  {
    name: 'Moroka Swallows',
    slug: 'moroka-swallows',
    shortName: 'Swallows',
    country: 'South Africa',
    externalId: 'psl-moroka-swallows',
    primaryColour: '#CC0000',
    secondaryColour: '#000000',
    city: 'Johannesburg',
    venueExternalId: 'psl-venue-dobsonville',
    venueName: 'Dobsonville Stadium',
    venueCapacity: 20000,
  },
  {
    name: 'Maritzburg United',
    slug: 'maritzburg-united',
    shortName: 'Maritzburg',
    country: 'South Africa',
    externalId: 'psl-maritzburg-united',
    primaryColour: '#800080',
    secondaryColour: '#FFFFFF',
    city: 'Pietermaritzburg',
    venueExternalId: 'psl-venue-harry-gwala',
    venueName: 'Harry Gwala Stadium',
    venueCapacity: 20000,
  },
  {
    name: 'Royal AM',
    slug: 'royal-am',
    shortName: 'Royal AM',
    country: 'South Africa',
    externalId: 'psl-royal-am',
    primaryColour: '#800080',
    secondaryColour: '#FFD700',
    city: 'Durban',
    venueExternalId: 'psl-venue-chatsworth',
    venueName: 'Chatsworth Stadium',
    venueCapacity: 20000,
  },
  {
    name: 'Marumo Gallants',
    slug: 'marumo-gallants',
    shortName: 'Gallants',
    country: 'South Africa',
    externalId: 'psl-marumo-gallants',
    primaryColour: '#FF8C00',
    secondaryColour: '#000000',
    city: 'Limpopo',
    venueExternalId: 'psl-venue-peter-mokaba',
    venueName: 'Peter Mokaba Stadium',
    venueCapacity: 40929,
  },
];

export const PSL_VENUE_EXTERNAL_IDS = [
  'psl-venue-loftus',
  'psl-venue-fnb',
  'psl-venue-orlando',
  'psl-venue-lucas-moripe',
  'psl-venue-dhl-newlands',
  'psl-venue-danie-craven',
  'psl-venue-mbombela',
  'psl-venue-peter-mokaba',
  'psl-venue-moses-mabhida',
  'psl-venue-princess-magogo',
  'psl-venue-nelson-mandela-bay',
  'psl-venue-dobsonville',
  'psl-venue-harry-gwala',
  'psl-venue-chatsworth',
];
