export enum ErrorCode {
  // Identity
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  OTP_EXPIRED = 'OTP_EXPIRED',
  OTP_INVALID = 'OTP_INVALID',

  // Football
  FIXTURE_NOT_FOUND = 'FIXTURE_NOT_FOUND',
  COMPETITION_NOT_FOUND = 'COMPETITION_NOT_FOUND',

  // Fantasy
  INVALID_SQUAD_COMPOSITION = 'INVALID_SQUAD_COMPOSITION',
  TRANSFER_DEADLINE_PASSED = 'TRANSFER_DEADLINE_PASSED',
  DUPLICATE_PLAYER = 'DUPLICATE_PLAYER',
  MAX_PLAYERS_PER_CLUB_EXCEEDED = 'MAX_PLAYERS_PER_CLUB_EXCEEDED',

  // GTS
  PREDICTION_LOCKED = 'PREDICTION_LOCKED',
  DUPLICATE_PREDICTION = 'DUPLICATE_PREDICTION',
  FIXTURE_NOT_OPEN = 'FIXTURE_NOT_OPEN',

  // Wallet
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',

  // General
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
